const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const assert = require('node:assert/strict');
const test = require('node:test');
const { pool } = require('../src/config/database');
const authService = require('../src/services/auth.service');
const empleadoService = require('../src/services/empleado.service');
const sucursalService = require('../src/services/sucursal.service');
const solicitudService = require('../src/services/solicitud.service');
const marcacionService = require('../src/services/marcacion.service');

test.after(async () => {
  await pool.end();
});

test('Integration tests for features in migration 032', async () => {
  // 1. Get a plan
  const planRes = await pool.query("SELECT id FROM planes WHERE codigo = 'starter' LIMIT 1");
  const planId = planRes.rows[0]?.id;
  if (!planId) {
    console.log('Skipping integration test: no starter plan found');
    return;
  }

  // 2. Register a tenant with admin_cedula
  const randomSuffix = Date.now() + Math.floor(Math.random() * 1000);
  const tenantPayload = {
    nombre: `Empresa Test 032 ${randomSuffix}`,
    identificacion_fiscal: `17929${randomSuffix}`,
    email: `test-032-${randomSuffix}@empresa.local`,
    telefono: '099999999',
    direccion: 'Av. Test 123',
    plan_id: planId,
    admin_nombre: 'AdminTest032',
    admin_apellido: 'UserTest032',
    admin_email: `admin-032-${randomSuffix}@empresa.local`,
    admin_password: 'Password123*',
    admin_cedula: '1723456789',
  };

  const regResult = await authService.registerTenant(tenantPayload);
  assert.ok(regResult.user);
  assert.equal(regResult.user.cedula, '1723456789');

  const empresaId = regResult.user.empresa_id;

  // Verify findUserById returns cedula
  const user = await authService.findUserById(regResult.user.id);
  assert.equal(user.cedula, '1723456789');

  // 3. Create a branch (sucursal)
  const sucursalPayload = {
    nombre: 'Sucursal Test 032',
    codigo: `SUC${randomSuffix}`,
    direccion: 'Calle Falsa 123',
    ciudad: 'Quito',
    latitud: -0.180653,
    longitud: -78.467834,
    radio_metros: 100,
    estado: 'activa',
  };
  const sucursal = await sucursalService.createSucursal(empresaId, sucursalPayload);
  assert.ok(sucursal.id);

  // 4. Create employees
  // Employee 1: will be Jefe de Almacén
  const emp1Payload = {
    nombres: 'Jefe',
    apellidos: 'Almacen',
    email: `jefe-${randomSuffix}@empresa.local`,
    crear_usuario: true,
    rol_acceso: 'EMPLEADO',
    password_acceso: 'Password123*',
    sucursal_habitual_id: sucursal.id,
    estado: 'activo',
    cedula: '1700000001',
  };
  const jefeEmpleado = await empleadoService.createEmpleado(empresaId, emp1Payload);
  assert.ok(jefeEmpleado.id);
  // Verify autogenerated code
  assert.match(jefeEmpleado.codigo, /^EMP-\d{6}$/);

  // Employee 2: normal employee
  const emp2Payload = {
    nombres: 'Juan',
    apellidos: 'Perez',
    email: `juan-${randomSuffix}@empresa.local`,
    crear_usuario: true,
    rol_acceso: 'EMPLEADO',
    password_acceso: 'Password123*',
    sucursal_habitual_id: sucursal.id,
    estado: 'activo',
    cedula: '1700000002',
  };
  const empleado = await empleadoService.createEmpleado(empresaId, emp2Payload);
  assert.ok(empleado.id);
  assert.match(empleado.codigo, /^EMP-\d{6}$/);

  // 5. Verify Employee code cannot be changed on update
  const originalCode = empleado.codigo;
  const updatedEmp = await empleadoService.updateEmpleado(empresaId, empleado.id, {
    codigo: 'CHANGE-ME',
    nombres: 'Juan Modificado',
  });
  assert.equal(updatedEmp.codigo, originalCode); // Remains unchanged!
  assert.equal(updatedEmp.nombres, 'Juan Modificado');

  // 6. Assign Jefe to Sucursal
  const updatedSucursal = await sucursalService.updateSucursal(empresaId, sucursal.id, {
    jefe_empleado_id: jefeEmpleado.id,
  });
  assert.equal(updatedSucursal.jefe_empleado_id, jefeEmpleado.id);

  // Verify listSucursales returns jefe names
  const sucursalesList = await sucursalService.listSucursales({ empresaId });
  const foundSuc = sucursalesList.items.find(s => s.id === sucursal.id);
  assert.ok(foundSuc);
  assert.equal(foundSuc.jefe_nombres, 'Jefe');
  assert.equal(foundSuc.jefe_apellidos, 'Almacen');

  // 7. Verify reject jefe_empleado_id from different company
  const dummyUuid = 'c0a80101-0000-0000-0000-000000000000';
  await assert.rejects(
    () => sucursalService.updateSucursal(empresaId, sucursal.id, { jefe_empleado_id: dummyUuid }),
    /El jefe de almacén indicado no pertenece a la empresa/
  );

  // 8. Solicitud approvals
  const authEmpleado = { usuario_id: empleado.usuario_id, rol: 'EMPLEADO' };
  const authJefe = { usuario_id: jefeEmpleado.usuario_id, rol: 'EMPLEADO' };

  // Create leave request for Juan Perez (Employee 2)
  const today = new Date().toISOString().slice(0, 10);
  const nextWeek = new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
  const solicitud = await solicitudService.createSolicitud({
    empresaId,
    auth: authEmpleado,
    payload: {
      tipo: 'permiso',
      fecha_inicio: today,
      fecha_fin: today,
      hora_inicio: '08:00',
      hora_fin: '12:00',
      motivo: 'Cita medica',
    },
  });
  assert.ok(solicitud.id);
  assert.equal(solicitud.estado, 'pendiente');

  // Review Solicitud - Employee cannot approve their own request
  await assert.rejects(
    () => solicitudService.reviewSolicitud({
      empresaId,
      solicitudId: solicitud.id,
      reviewerId: empleado.usuario_id,
      auth: authEmpleado,
      decision: 'aprobar',
    }),
    /Un jefe de almacén no puede aprobar sus propias solicitudes/
  );

  // Review Solicitud - Jefe de Almacen validates Juan's request (should transition to 'validada')
  const validatedSolicitud = await solicitudService.reviewSolicitud({
    empresaId,
    solicitudId: solicitud.id,
    reviewerId: jefeEmpleado.usuario_id,
    auth: authJefe,
    decision: 'aprobar',
  });
  assert.equal(validatedSolicitud.estado, 'validada');
  assert.equal(validatedSolicitud.validado_por, jefeEmpleado.usuario_id);

  // Finally, RRHH/Admin approves the request (should transition to 'aprobada')
  const authAdmin = { usuario_id: regResult.user.id, rol: 'ADMIN_EMPRESA' };
  const approvedSolicitud = await solicitudService.reviewSolicitud({
    empresaId,
    solicitudId: solicitud.id,
    reviewerId: regResult.user.id,
    auth: authAdmin,
    decision: 'aprobar',
  });
  assert.equal(approvedSolicitud.estado, 'aprobada');
  assert.equal(approvedSolicitud.revisado_por, regResult.user.id);

  // Create leave request for Jefe (Employee 1)
  const jefeSolicitud = await solicitudService.createSolicitud({
    empresaId,
    auth: authJefe,
    payload: {
      tipo: 'vacaciones',
      fecha_inicio: nextWeek,
      fecha_fin: nextWeek,
      motivo: 'Descanso',
    },
  });
  assert.ok(jefeSolicitud.id);

  // Jefe cannot approve their own request
  await assert.rejects(
    () => solicitudService.reviewSolicitud({
      empresaId,
      solicitudId: jefeSolicitud.id,
      reviewerId: jefeEmpleado.usuario_id,
      auth: authJefe,
      decision: 'aprobar',
    }),
    /Un jefe de almacén no puede aprobar sus propias solicitudes/
  );

  // 9. Device UUID control (Marcaciones / Buddy Punching)
  const qrToken = sucursal.qr_token;
  const mockGps = { latitud: sucursal.latitud, longitud: sucursal.longitud, precision_gps: 5 };

  // First mark by Employee 2 (Juan Perez) - should lock device
  const deviceA = `device-uuid-A-${randomSuffix}`;
  const mark1 = await marcacionService.registrarMarcacion({
    empresaId,
    auth: authEmpleado,
    payload: {
      qr_token: qrToken,
      tipo: 'entrada',
      dispositivo_uuid: deviceA,
      ...mockGps,
    },
  });
  assert.equal(mark1.marcacion.estado, 'aceptada');

  // Verify employee's dispositivo_uuid is locked to deviceA
  const empUpdated = await empleadoService.findEmpleadoById(empresaId, empleado.id);
  assert.equal(empUpdated.dispositivo_uuid, deviceA);

  // Sub-mark with different device should fail
  await assert.rejects(
    () => marcacionService.registrarMarcacion({
      empresaId,
      auth: authEmpleado,
      payload: {
        qr_token: qrToken,
        tipo: 'salida',
        dispositivo_uuid: 'different-device-uuid',
        ...mockGps,
      },
    }),
    /Este usuario tiene otro dispositivo móvil registrado/
  );

  // Mark by different employee (Jefe) using same device (deviceA) should fail
  await assert.rejects(
    () => marcacionService.registrarMarcacion({
      empresaId,
      auth: authJefe,
      payload: {
        qr_token: qrToken,
        tipo: 'entrada',
        dispositivo_uuid: deviceA,
        ...mockGps,
      },
    }),
    /Este dispositivo ya está registrado para otro empleado/
  );
});
