import { useEffect, useState } from 'react';
import { Download, Eye, RotateCcw, Search } from 'lucide-react';
import PageHeader from '../../components/common/PageHeader';
import PanelTitle from '../../components/common/PanelTitle';
import * as service from '../../services/auditoriaService';

export default function Auditoria(){
  const [filters,setFilters]=useState({search:'',entidad:'',metodo:'',fecha_desde:'',fecha_hasta:''});const [data,setData]=useState({items:[],total:0});const [selected,setSelected]=useState(null);const [loading,setLoading]=useState(false);
  async function load(){setLoading(true);try{setData(await service.listAuditoria({...filters,limit:100}));}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);function change(field,value){setFilters(current=>({...current,[field]:value}));}
  return <>
    <PageHeader title="Auditoria" description="Trazabilidad de cambios, actor, ruta, IP y datos modificados." actions={<button className="outline-button" onClick={()=>service.exportarAuditoria(filters)}><Download size={16}/>Exportar CSV</button>}/>
    <div className="panel"><PanelTitle title="Filtros" subtitle="Consulta eventos administrativos y operativos"/><div className="toolbar-grid"><label className="search-box inline-search"><Search size={16}/><input value={filters.search} onChange={e=>change('search',e.target.value)} placeholder="Usuario, accion o ruta"/></label><input placeholder="Entidad" value={filters.entidad} onChange={e=>change('entidad',e.target.value)}/><select value={filters.metodo} onChange={e=>change('metodo',e.target.value)}><option value="">Todos los metodos</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select><input type="date" value={filters.fecha_desde} onChange={e=>change('fecha_desde',e.target.value)}/><input type="date" value={filters.fecha_hasta} onChange={e=>change('fecha_hasta',e.target.value)}/><button className="outline-button" onClick={load}><RotateCcw size={16}/>Aplicar</button></div></div>
    {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal-panel" onClick={e=>e.stopPropagation()}><PanelTitle title="Detalle de auditoria" subtitle={`${selected.metodo} ${selected.ruta}`}/><div className="settings-grid"><label>Usuario<input readOnly value={selected.usuario_email||'Sistema'}/></label><label>IP<input readOnly value={selected.ip||'-'}/></label><label>Estado HTTP<input readOnly value={selected.estado_http||'-'}/></label><label>Fecha<input readOnly value={new Date(selected.creado_en).toLocaleString()}/></label></div><pre className="audit-json">{JSON.stringify(selected.metadata,null,2)}</pre><div className="form-actions"><button className="outline-button" onClick={()=>setSelected(null)}>Cerrar</button></div></div></div>}
    <div className="panel"><PanelTitle title="Eventos registrados" subtitle={loading?'Cargando...':`${data.total||0} eventos`}/><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Usuario</th><th>Accion</th><th>Entidad</th><th>Ruta</th><th>IP</th><th>HTTP</th><th></th></tr></thead><tbody>{data.items?.length?data.items.map(item=><tr key={item.id}><td>{new Date(item.creado_en).toLocaleString()}</td><td>{item.usuario_email||'Sistema'}</td><td>{item.accion}</td><td>{item.entidad}</td><td>{item.ruta}</td><td>{item.ip||'-'}</td><td><span className={`status-pill ${item.estado_http>=400?'danger':''}`}>{item.estado_http}</span></td><td><button className="icon-button" aria-label="Ver detalle" onClick={()=>setSelected(item)}><Eye size={16}/></button></td></tr>):<tr><td colSpan="8">No hay eventos para mostrar.</td></tr>}</tbody></table></div></div>
  </>;
}
