BEGIN;

ALTER TABLE pagos
ADD COLUMN IF NOT EXISTS comprobante_nombre VARCHAR(255),
ADD COLUMN IF NOT EXISTS comprobante_tipo VARCHAR(120),
ADD COLUMN IF NOT EXISTS comprobante_data BYTEA,
ADD COLUMN IF NOT EXISTS comprobante_subido_en TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW();

COMMIT;
