BEGIN;

ALTER TABLE facturas
ADD COLUMN IF NOT EXISTS pdf_nombre VARCHAR(255),
ADD COLUMN IF NOT EXISTS pdf_tipo VARCHAR(120),
ADD COLUMN IF NOT EXISTS pdf_data BYTEA,
ADD COLUMN IF NOT EXISTS pdf_subido_en TIMESTAMPTZ;

COMMIT;
