ALTER TABLE empresas
  ADD COLUMN IF NOT EXISTS logo_nombre VARCHAR(255),
  ADD COLUMN IF NOT EXISTS logo_tipo VARCHAR(120),
  ADD COLUMN IF NOT EXISTS logo_data BYTEA,
  ADD COLUMN IF NOT EXISTS logo_storage_provider VARCHAR(40),
  ADD COLUMN IF NOT EXISTS logo_storage_bucket VARCHAR(120),
  ADD COLUMN IF NOT EXISTS logo_storage_key TEXT,
  ADD COLUMN IF NOT EXISTS logo_storage_url TEXT,
  ADD COLUMN IF NOT EXISTS logo_subido_en TIMESTAMPTZ;
